FROM eclipse-temurin:21.0.5_11-jdk-alpine@sha256:ee09bfd4218b1296231588981fd1e4f74843ca585d5fd6a37bf6078e34c847c7

ADD https://nilhcem.github.io/FakeSMTP/downloads/fakeSMTP-latest.zip /fakeSMTP-latest.zip
RUN unzip /fakeSMTP-latest.zip
VOLUME ["/var/mail"]
EXPOSE 25

ENTRYPOINT ["java","-jar","/fakeSMTP-2.0.jar","--background", "--output-dir", "/var/mail", "--port", "25", "--start-server"]
