FROM openjdk:8-jdk

COPY ./va-virkailija/target/uberjar/virkailija-0.1.0-SNAPSHOT-standalone.jar /app/va-virkailija/app.jar
COPY ./va-virkailija/config/defaults.edn /app/va-virkailija/config/defaults.edn
COPY ./va-virkailija/config/docker-compose-test.edn /app/va-virkailija/config/docker-compose-test.edn

WORKDIR /app/va-virkailija
ENV environment=dev
ENV configdefaults=/app/va-virkailija/config/defaults.edn
ENV config=/app/va-virkailija/config/docker-compose-test.edn
ENTRYPOINT ["java", "-jar", "app.jar"]
