FROM mcr.microsoft.com/playwright:v1.47.2-focal@sha256:12c49ccd20c51c02c6c46307cb219cb598955465fcd50b983db0b33e483ffd7d

COPY package.json package-lock.json .
RUN npm ci

COPY playwright playwright/
COPY soresu-form soresu-form/
COPY va-virkailija va-virkailija/
COPY run_playwright_tests_in_container.sh run_playwright_tests_in_container.sh

ENTRYPOINT ["./run_playwright_tests_in_container.sh"]
