FROM mcr.microsoft.com/playwright:v1.49.1-noble@sha256:70e367e0cbf60340a5b5fd562f6247a34eb3196efab9f88a3dd56482d9fe09d2

COPY package.json package-lock.json .
RUN --mount=type=cache,target=/root/.npm npm ci

COPY playwright playwright/
COPY soresu-form soresu-form/
COPY va-virkailija va-virkailija/

ENTRYPOINT ["/usr/bin/npm", "run", "playwright:test"]

