FROM node:24.14.0-bookworm@sha256:5a593d74b632d1c6f816457477b6819760e13624455d587eef0fa418c8d0777b

COPY . /app
WORKDIR /app

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb

RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional ssh less jq
RUN npm ci

CMD ["/app/entrypoint.sh"]
