FROM node:24.18.0-bookworm@sha256:5711a0d445a1af54af9589066c646df387d1831a608226f4cd694fc59e745059

COPY . /app
WORKDIR /app

RUN curl \
    "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_arm64/session-manager-plugin.deb" \
    -o "/tmp/session-manager-plugin.deb"
RUN dpkg -i /tmp/session-manager-plugin.deb

RUN apt-get update && apt-get install -y awscli bash socat daemonize netcat-traditional ssh less jq
RUN npm ci

CMD ["/app/entrypoint.sh"]
