FROM amazonlinux:2023@sha256:d8566f52e9af381444249674c43132920e6b7f4e1355d771b317ca4ac4ccab93

RUN yum install -y \
    procps \
    findutils \
    which \
    bash

# Fargate 1.4 ships with SSM agent, we just need to wait for incoming commands
ENTRYPOINT ["/usr/bin/sleep", "infinity"]
