FROM amazonlinux:2023@sha256:b0737d724480361f137d428136721fff45f56792d650f4675d1e5732bb1104e4

RUN yum install -y \
    procps \
    findutils \
    which \
    bash

# Fargate 1.4 ships with SSM agent, we just need to wait for incoming commands
ENTRYPOINT ["/usr/bin/sleep", "infinity"]
