FROM amazonlinux:2023@sha256:51b2a6d2c7f920500b9a061b3f4776319ed40094ec4b75dcb2a4e3a1bdaed37a

RUN yum install -y \
    procps \
    findutils \
    which \
    bash

# Fargate 1.4 ships with SSM agent, we just need to wait for incoming commands
ENTRYPOINT ["/usr/bin/sleep", "infinity"]
