update arviot
set status = :status,
    overridden_answers = :overridden_answers,
    budget_granted = :budget_granted,
    summary_comment = :summary_comment,
    changelog = :changelog,
    presenter_role_id = :presenter_role_id,
    roles = :roles,
    rahoitusalue = :rahoitusalue,
    talousarviotili = :talousarviotili,
    perustelut = :perustelut,
    costs_granted = :costs_granted,
    use_overridden_detailed_costs = :use_overridden_detailed_costs,
    presentercomment = :presentercomment,
    academysize = :academysize,
    seuranta_answers = :seuranta_answers,
    tags = :tags,
    oppilaitokset = :oppilaitokset
where hakemus_id = :hakemus_id
