#!./pouta-venv/bin/python
import json
import sys
import subprocess
from subprocess import Popen, PIPE, call

output, error = Popen(["./openstack_inventory.py"], stdout = PIPE, stderr= PIPE).communicate()
inventory = json.loads(output)

if len(sys.argv) < 2:
  print "Usage " + sys.argv[0] + " [host]"
  print "Available hosts:"
  hosts = inventory['_meta']['hostvars'].keys()
  print '\n'.join(str(k) for k in sorted(hosts))
  exit(2)

if sys.argv[1] in inventory['_meta']['hostvars']:
  ip = inventory['_meta']['hostvars'][sys.argv[1]]['ansible_ssh_host']
  ssh_arguments = ' '.join(map(str, sys.argv[2::]))
  output, error = subprocess.Popen(['ssh', '-o', 'StrictHostKeyChecking=no', '-F', 'ssh.config', ip, ssh_arguments],stdout = subprocess.PIPE, stderr= subprocess.PIPE).communicate()
  print error
  print output
else:
  print "Unknown host " + sys.argv[1]
