(ns oph.va.hakija.api.queries
  (:require [yesql.core :refer [defquery]]))

(defquery health-check "sql/hakija/healthcheck.sql")

(defquery create-avustushaku<! "sql/hakija/avustushaku/create.sql")
(defquery update-avustushaku! "sql/hakija/avustushaku/update.sql")
(defquery archive-avustushaku! "sql/hakija/avustushaku/archive.sql")
(defquery list-avustushaut "sql/hakija/avustushaku/list.sql")
(defquery list-avustushaut-by-status "sql/hakija/avustushaku/list-by-status.sql")
(defquery get-avustushaku"sql/hakija/avustushaku/get.sql")
(defquery get-avustushaku-by-status"sql/hakija/avustushaku/get-by-status.sql")
(defquery create-avustushaku-role<! "sql/hakija/avustushaku/create-role.sql")
(defquery get-avustushaku-role "sql/hakija/avustushaku/get-role.sql")
(defquery update-avustushaku-role! "sql/hakija/avustushaku/update-role.sql")
(defquery delete-avustushaku-role! "sql/hakija/avustushaku/delete-role.sql")
(defquery get-avustushaku-roles "sql/hakija/avustushaku/get-roles.sql")
(defquery list-hakemukset-by-avustushaku "sql/hakija/hakemus/list-by-avustushaku.sql")
(defquery list-hakemus-decision-email-statuses "sql/hakija/hakemus/list-hakemus-decisions-by-avustushaku.sql")
(defquery copy-form<! "sql/hakija/form/copy.sql")
(defquery get-form-by-avustushaku "sql/hakija/form/get-by-avustushaku.sql")
(defquery archive-form! "sql/hakija/form/archive.sql")
(defquery update-form! "sql/hakija/form/update.sql")

(defquery list-attachments "sql/hakija/attachment/list.sql")
(defquery list-attachment-versions "sql/hakija/attachment/list-versions.sql")
(defquery list-attachments-by-avustushaku "sql/hakija/attachment/list-by-avustushaku.sql")
(defquery attachment-exists? "sql/hakija/attachment/exists.sql")
(defquery download-attachment "sql/hakija/attachment/download.sql")
(defquery download-attachment-version "sql/hakija/attachment/download-version.sql")

(defquery get-hakemus "sql/hakija/hakemus/get-by-id.sql")
(defquery get-hakemus-with-answers "sql/hakija/hakemus/get-by-id-with-answers.sql")
(defquery list-hakemus-change-requests "sql/hakija/hakemus/list-change-requests-by-id.sql")
(defquery update-hakemus-status<! "sql/common/hakija/hakemus/update-status.sql")
(defquery lock-hakemus "sql/common/hakija/hakemus/lock.sql")
(defquery close-existing-hakemus! "sql/common/hakija/hakemus/close-existing.sql")

(defquery add-hakemus-decision! "sql/hakija/hakemus/add-hakemus-decision.sql")

(defquery get-submission "sql/hakija/submission/get-by-id.sql")
