(ns oph.soresu.common.validation-spec
  (:require [speclj.core :refer :all]
            [oph.soresu.common.validation :refer :all]))

(describe "common validation"
  (it "validates email"
    (should= true (email-address? "user@example.com"))
    (should= true (email-address? "first.last@example.com"))
    (should= true (email-address? "First.LAST@example.com"))
    (should= true (email-address? "valid.email@my-example.DOT.com"))
    (should= true (email-address? "valid+param@example.com"))
    (should= false (email-address? "nosuch"))
    (should= false (email-address? "example.com"))
    (should= false (email-address? "invalid@example"))
    (should= false (email-address? "invalid@example,com"))
    (should= false (email-address? "invalid@example.,com"))
    (should= false (email-address? "first last@example.com"))
    (should= false (email-address? "first. last@example.com"))
    (should= false (email-address? "first .last@example.com"))
    (should= false (email-address? "äö@example.com"))
    (should= false (email-address? "invalid.em%0Ail@example.com"))
    (should= false (email-address? "invalid.em%0ail@example.com"))
    (should= false (email-address? " user@example.com"))
    (should= false (email-address? ";user@example.com"))
    (should= false (email-address? "user@example.com "))
    (should= false (email-address? "user@example.com;"))
    (should= false (email-address? "Matti Meikalainen <matti@example.com>"))
    (should= false (email-address? "Matti Meikälainen <matti@example.com>"))
    (should= false (email-address? "user1@example.com user2@example.com"))
    (should= false (email-address? "user1@example.com, user2@example.com"))
    (should= false (email-address? "user1@example.com; user2@example.com"))
    (should= false (email-address? "user1@example.com; user2@example.com"))
    (should= false (email-address? ""))
    (should= false (email-address? 42))
    (should= false (email-address? nil)))

  (it "validates Finnish business-id"
    (should= true (finnish-business-id? "1629284-5"))
    (should= true (finnish-business-id? "0165761-0"))
    (should= true (finnish-business-id? "0208201-1"))
    (should= false (finnish-business-id? "1629284-6"))
    (should= false (finnish-business-id? "165761-0"))
    (should= false (finnish-business-id? " 0208201-1"))
    (should= false (finnish-business-id? ";0208201-1"))
    (should= false (finnish-business-id? "0208201-1 "))
    (should= false (finnish-business-id? "0208201-1;"))
    (should= false (finnish-business-id? ""))
    (should= false (finnish-business-id? 42))
    (should= false (finnish-business-id? nil))))
