name: Build
on:
  workflow_call:
    inputs:
      checkout-ref:
        description: "Commit SHA or ref to checkout (optional)"
        required: false
        type: string

concurrency: build-${{ inputs.checkout-ref || github.ref }}

env:
  DOCKER_BUILDKIT: "1" # BuildKit is enabled by default starting in Docker v23, Ubuntu 22.04 has an older version

defaults:
  run:
    shell: bash

jobs:
  radiator-status-in-progress:
    name: Send in-progress status to radiator
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-24.04
    steps:
      - run: |
          curl \
            -H "AUTH_TOKEN: ${{ secrets.RADIATOR_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -X PUT \
            https://radiator.continuous-services.services/api/v2/buildstatus/valtionavustus/deploy-dev \
            -d '{"status": "inProgress"}'

  build:
    name: 01-build.sh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref || '' }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 01-build.sh
        run: ./deploy-scripts/01-build.sh

  other-tests:
    name: 02-other-tests.sh
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref || '' }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run 02-other-tests.sh
        run: ./deploy-scripts/02-other-tests.sh

  playwright-tests:
    name: 03-playwright-tests.sh (shard ${{ matrix.shard }}/${{ matrix.total_shards }})
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5, 6]
        total_shards: [6]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref || '' }}
      - name: Run 03-playwright-tests.sh
        run: ./deploy-scripts/03-playwright-tests.sh
        env:
          PLAYWRIGHT_WORKERS: 3 # GH Actions will choke to death with more workers
          PLAYWRIGHT_SHARD: ${{ matrix.shard }}
          PLAYWRIGHT_SHARDS_AMOUNT: ${{ matrix.total_shards }}
      - name: Upload Playwright results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: playwright-blob-${{ matrix.shard }}
          path: playwright-results/blob-report
          retention-days: 1

  lint:
    name: 04-lint.sh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.checkout-ref || '' }}
      - name: Run 04-lint.sh
        run: ./deploy-scripts/04-lint.sh

  radiator-status-failure:
    name: Send failure status to radiator
    needs: [ build, other-tests, playwright-tests, lint ]
    if: ${{ always() && contains(needs.*.result, 'failure') && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-24.04
    steps:
      - run: |
          curl \
            -H "AUTH_TOKEN: ${{ secrets.RADIATOR_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -X PUT \
            https://radiator.continuous-services.services/api/v2/buildstatus/valtionavustus/deploy-dev \
            -d '{"status": "failure"}'
