name: Refresh BOM and POM on Renovate PR

on:
  workflow_call:

concurrency:
  group: renovate-bom-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: false

jobs:
  refresh-bom:
    if: github.actor == 'valtionavustus-renovate[bot]' &&
        github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout PR head branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Run BOM refresh script
        run: ./scripts/build_and_refresh_pom_and_bom.sh

      - name: Commit refreshed artifacts (if changed)
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: "chore(bom): refresh pom.xml & bom.json after Renovate updates"
          file_pattern: "pom.xml bom.json"
