name: Run tests after BOM refresh

on:
  workflow_run:
    workflows: ["Refresh BOM and POM on Renovate PR"]
    types: [completed]

jobs:
  rerun-tests:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.repository.full_name == github.repository &&
      github.event.workflow_run.actor.login == 'valtionavustus-renovate[bot]'
    uses: ./.github/workflows/_build.yaml
    secrets: inherit
    with:
      checkout-ref: ${{ github.event.workflow_run.head_sha }}
